### ISSUE TITLE
Change type of `Verify`

### ISSUE THREAD

**Issue by mariaschett** [project-oak/transparent-release#162]
Currently `Verify` fails with [an error](https://github.com/project-oak/transparent-release/blob/c94a5a6237d03909afb0acf98c5047658b23081a/internal/verifier/verifier.go#L32). 

This does not allow us to distinguish between
- the process of verifying failed, e.g., a file was not found, and
- the verification itself did not succeed, e.g., the binary digest does not match.

I propose to add a `VerificationReport`:

```go
// VerificationReport reports the result of Verify. The executive summary is `IsVerified`.
struct VerificationReport {
   // Holds if Verify succeeded.
    IsVerified: bool,
    // Justification for IsVerified. If there are several failures, we can collect all of them and also combine `VerificationReport`s.
    Justifications : []string,
}
```

and change the signature of `Verify` to:

```go
Verify() VerificationReport, error
```

WDYT, @rbehjati ?

**Comment by rbehjati** [comment]
How will `VerificationReport` and the `Justifications` be used? If they will be printed out in a log, I don't see much difference between the two approaches.

A better pattern that we often use is to return `ValidatedBlah, error`. That way you can pass `ValidatedBlah` around, and be certain that the object that you are working with, and all its fields, are validated.

**Comment by rbehjati** [comment]
Sounds good to me, assuming that it is clear what should go to `VerificationReport`, and what should be an early error. I see how it is favourable from a usability perspective to collect and report all issues at once. This works if the issues are independent of each other, but otherwise showing a long list of issues to the user can be confusing. 

On the other hand, it is generally favourable to fail early, and avoid doing unnecessary computation. The computation is light-weight in case of checking reference values. But does it also apply to `ReproducibleProvenanceVerifier` that fetches the source code and runs the `docker run` command? I think in that case we'd want to return early, and I am not sure what would go into `VerificationReport`.

**Comment by mariaschett** [comment]
Sounds good! 

I suggest the following:
- If the process of verification fails, then return an error.
- Otherwise try as many independent verification steps as possible. For efficiency, e.g., in the `ReproducibleVerifier` we could still return an error instead of a `VerificationReport`.

I'll give it a try and see how it goes!

**Comment by rbehjati** [comment]
Sounds good. Thanks :)
