### ISSUE TITLE
What is the right SLSA Schema Format?

### ISSUE THREAD

**Issue by jul-sh** [project-oak/transparent-release#20]
We presently use a JSON schema to specify the shape of the expected SLSA buildType. While I went with a JSON schema, this was done initially just to have *some* clearly defined format. It doesn't have to be JSON schema specifically and there's a few pros & cons to them:

Pros:
- Machine readable, hence clearly defined
- Existing tools for both validation of schemas and for generating example data off them
- Open standard

Cons:
- They're like actually quite hard to read for humans
- We can't actually use them to parse JSON files, only to validate. Hence we require go structs which essentially duplicate the schema (in less detail). See PR #16 for deets.

Thoughts? Ideas? :) cc @rbehjati @tiziano88 

[This issue is related to #15, probably a superset of it].

**Comment by jul-sh** [comment]
@tiziano88 suggested just using go structs for now, and I'm like personally rather partial to that idea. Imo the less duplication the better. If the go structs that represent data internally could also validate it that'd be great. 

The downside is that they don't seem to be quite as specific. Eg unmarshaling JSON silently fails if eg keys are not defined. We can write logic to catch it, but this does come at the expense of human readability. 

Imo this approach might be a good fit anyways though, at least initially. As we're still at the beginning of this project it's reasonable to think that we'll make schema changes a bit more frequently at this point. Only maintaining a single representation makes that a lot easier.

Once our schema is more stable we can always offer schema's of different formats for improved human readability.

**Comment by tiziano88** [comment]
Since we need a Go struct *at some point* anyways, I indeed suggest starting from just that. We can document additional constraints (e.g. number of elements in a slice, ordering, allowed empty fields) as comments on the struct fields for now, and implement a validator / parser method to enforce those constraints. Unfortunately Go makes the usual [parse, don't validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/) approach not very easy to implement because of its poor type system, but we have to work with that (and we can improve things over time). 

Once we have this struct, we can write most unit tests based on it (we don't need to deserialize a JSON / TOML file each time), and we can even decide to switch between JSON / TOML separately. IMO the validation logic should not be completely tied to JSON schema, it should be a validation of a Go struct (so that it can also be tested in our own code).

Annoyingly, we would probably have to document when a function expects an already validated struct vs when it is expected to the validation itself -- this is a consequence of the poor type system I mentioned above. Maybe there is value in having a struct for (de)serialization, with just the outer layer of the schema, and then performing the parsing into a more precise struct with more typesafe fields, but I'm not sure this is all that worthwhile in Go given that there is nothing in principle that would prevent creating directly the "parsed" struct, bypassing the parsing logic. Maybe if the parsed type is not exported it would work? But then I'm not sure if it's possible to test things, or if we need to stick to types that are exported.

**Comment by tiziano88** [comment]
> Fair, we can do that. :) The downside of this approach is that we commit to maintaining isomorphic structs. At minimum that's the schema and the struct (or even multiple schemas and the struct, in our case then Struct, SLSA-JSON, TOML). I'm not entirely convinced that's useful, but I'm also not vetoing it.

Which isomorphic structs?

Do you mean the TOML and the JSON structs? Those can be the same struct, just with the appropriate serialization annotations.

Or do you mean the deserialized and the validated structs? Those are not isomorphic, since the result of validating the deserialized struct may or may not be the validated struct, so there is no direct morphism from the deserialized struct to the validated struct, hence they are not isomorphic.

> What's your take on #16 (also #3)? Do we want to go ahead with that PR and refactor away the JSON schema later, or do we want to block this PR until we update to using just go? @tiziano88

Personally I would just skip the JSON schema stuff entirely, but add some hand-written Go validation logic. But I imagine you added it there also because you wanted a SLSA build type URL that points to the schema, right? Anyways I don't feel too bad if we keep the current URL but we just postpone publishing the actual JSON schema there to a later time. Or we can just have a file that says "look at the Go struct" for now (as a hint for humans, not something machine readable of course). Let's make things work for us and then we can think how to publish schemas and validators for external use.

**Comment by jul-sh** [comment]
Also worth noting that depending on the conclusion drawn in https://github.com/project-oak/transparent-release/pull/16#discussion_r800474868, we may very well already have an internal go struct post #16. 

At that point the single internal go struct. We can then later look at updating how we validate SLSA files.

**Comment by jul-sh** [comment]
> Do you mean the TOML and the JSON structs? Those can be the same struct, just with the appropriate serialization annotations.

Yes, I mean those annotations. :) And that's assuming there's just a difference in annotation, not in structure. There's also the validated struct, but agreed that's not isomorphic. 

Imo validation might be fine though, if sufficiently cheap we can just make every function validate it each time.
