### ISSUE TITLE
Transparent Release CLI producing different builds than manual Oak builds

### ISSUE THREAD

**Issue by jul-sh** [project-oak/transparent-release#25]
## Expected Behavior
Running the transparent release CLI on the testdata in https://github.com/project-oak/transparent-release/blob/main/testdata/build.toml yields the same binary hash as building the binary using Oak's `./scripts/docker_run` command with the same arguments. 

## Actual Behavior
Runnning the testdata yields the binary hash of `15dc16c42a4ac9ed77f337a4a3065a63e444c29c18c8cf69d6a6b4ae678dca5c `, as expected in the [testdata](https://github.com/project-oak/transparent-release/blob/main/testdata/build.toml). 

Running the same build using `./scripts/docker_run` yields a binary with the hash of `e4c5930c6c0e81f8d743da1597905df0fa66b0daf69c6bf92a5cbc561c79b127`.

## Steps to Reproduce the Problem

For testdata: see the expected hash in the testdata, or run the testdata as outlined in this repos readme.

For running the same build with Oak's `./scripts/docker_run`: 

1. Clone a fresh copy of the repo
2. Checkout the commit from testdata
3. Run `./scripts/docker_run` with the arguments provided in testdata's command key. 

For connivence, that's this command in a fresh clone: `git checkout 0f2189703c57845e09d8ab89164a4041c0af0a62 && ./scripts/docker_run ./scripts/runner build-functions-server && sha256sum ./oak_functions/loader/bin/oak_functions_loader`.

## Why this is happening

Further investigation is needed, but I'm fairly certain it boils down the fact that this CLI runs docker with different ENV variables and config than `./scripts/docker_run`.

In my case, `./scripts/docker_run` uses the following docker run command
```
docker run --rm --tty --env=TERM=xterm-256color --env=BAZEL_REMOTE_CACHE_ENABLED --env=BAZEL_GOOGLE_CREDENTIALS --env=HOST_UID --env=HOST_GID --volume=/usr/local/google/home/julsh/oak-tmp/bazel-cache:/home/docker/.cache/bazel --volume=/usr/local/google/home/julsh/oak-tmp/cargo-cache:/home/docker/.cargo --volume=/usr/local/google/home/julsh/oak-tmp/sccache-cache:/home/docker/.cache/sccache --volume=/usr/local/google/home/julsh/oak-tmp:/workspace --workdir=/workspace --network=host --volume=/var/run/docker.sock:/var/run/docker.sock --group-add=995 --interactive sha256:3ff688de7071c92700eb08462d846f92847f2a8ef33cb20638e52ae4133473c4 ./scripts/fix_docker_user_and_run './scripts/runner build-functions-server'
```

Whereas this CLI runs 
```
/usr/bin/docker run --volume=/tmp/release/oak:/workspace --workdir=/workspace --rm --tty gcr.io/oak-ci/oak@sha256:53ca44b5889e2265c3ae9e542d7097b7de12ea4c6a33785da8478c7333b9a320 ./scripts/runner build-functions-server
```

## Possible fixes

- More fully capture the docker env used?
- Use the CLI for Oak builds in general, or use it when generating provenances? Is it acceptable for provenances capture a different build than the canonical docker build config?

**Comment by tiziano88** [comment]
Another thing to check is the user running the process. I remember @ipetr0v investigated similar issues in the past where running as root or non-root would affect the final binary (though I also think @jul-sh checked that's not the case any more at some point?)

**Comment by tiziano88** [comment]
One thing to try is also to remove all the env variables from docker_run and see if it makes a difference (both in general (do random env variables affect the output, even if unrelated to the build?), and in particular for our build process)

**Comment by jul-sh** [comment]
Good pointers, confident we can trace it down more by playing with the flags, which I haven't done so far. :) — I guess either way though there's a question of this should be addressed architecturally. I worry we'd align `docker_run` and the CLI for now, but it seems they'd diverge again later

**Comment by rbehjati** [comment]
I think now that we have `./scripts/fix_docker_user_and_run` the command has to be something like `["./scripts/fix_docker_user_and_run" "'./scripts/runner build-functions-server'"]`. But that would also require passing the environment variables, and mounting the volumes (because the `./scripts/fix_docker_user_and_run` requires them). 

These are not very generic, and I think they should be passed as additional `docker run` flags.

**Comment by jul-sh** [comment]
How do people think we should best tackle this? 

A) Find a way to set the docker username in our provenance without passing host uid/guid? (Permissions give me headaches 😅)
B) Surrender and pass host uid/guid, exactly replicating the docker_run script
C) Debug Oak functions to try and fix hashes depending on the username

cc @rbehjati as the solution to this sort of depends on the wider interface of our CLI :)

**Comment by tiziano88** [comment]
I thought the conclusion is to just set the username to docker, regardless of UID / GID? It may well be that the simplest way of doing that is to use `fix_docker_user_and_run`, if it works I think that's fine.

**Comment by rbehjati** [comment]
Thanks for looking into this @jul-sh :)

I agree with your first comment about solving the problem architecturally. I think the right design, that is flexible and easy to maintain, is the one that makes the fewest assumptions about the details of the build configuration and setup. Based on that I would say that the buildConfig in the provenance should give a command that we run directly on the host machine instead of a command that we'd pass to `docker run` to execute. The command could be a script that itself runs `docker run`. 

I think this is similar to the idea of a meta-image that @tiziano88 previously mentioned in a few occasions.

This design raises a number of questions. In particular, 
1. How do we list all the required materials? 
1. How can we ensure that the command actually uses the listed materials for building the binary, and nothing else? 

If we have a trusted builder that automatically generates the provenances including a list of the materials, and signs it, then the second question is probably not relevant. The builder could be configured to include only the most important materials, for instance only the source code and the builder image as we currently have. We could even use the SLSA provenance metadata field to indicate that the list of materials is incomplete, or we could employ the idea of a release branch with venodred dependencies to avoid having to enumerate those dependencies in the list of materials. 

If we want to have provenances that can be verified automatically, then we have to find an answer to the second question. 
I think making provenances verifiable is a valuable goal to pursue. I don't know how exactly this can be engineered. But we could still require a source Git repository, and a builder image in the list of materials, and require the repository to contain a build script to use as the command in the buildConfig. We could perhaps use the idea of a meta-bulider docker image to somehow make sure that the build script (or generally the command) does not fetch anything other than the materials listed in the provenance. I don't know how exactly this can be done, or if it is feasible. But I think it is worth investigating.  

In the meantime, I think it is a good idea to proceed and fix the problem with UID/GID, if it does not require too much effort.

**Comment by rbehjati** [comment]
> Solutions could be:
> 
> * Add a command to make that user root (Should that command be done in the provenance, hardcoded as a step in our go code, as a script in Oak?)
> * Add a command that chowns the workspace dir to be accesible to the docker user (Should that command be done in the provenance, hardcoded as a step in our go code, as a script in Oak?)

I'd say preferably include it in the script in Oak, if that is not possible hardcode it in the go code.

**Comment by jul-sh** [comment]
The easiest solution for now would be https://github.com/project-oak/oak/pull/2542. Essentially that means a conceptual shift from seeing `scripts/docker_run` as "the idiomatic way to build Oak" towards "a connivence script that aliases host resources", while "reproducible builds" are done with less aliasing.

Imo that's probably not a bad solution, and I think preferable to both aliasing UID/GID / chowning the workdir / docker user creation etc.

**Comment by jul-sh** [comment]
RE the architectural concerns, I agree with your approach that we can solve this down the rod @rbehjati, thanks for writing down your thoughts. :) 

RE trusted builder vs reproducible builds, I think we can do both, and it'd be nice to do both. As the saying goes "trust but verify" 😅

**Comment by rbehjati** [comment]
https://github.com/project-oak/oak/pull/3152 fixes the issue on Oak.
